### ISSUE TITLE
Update to ILMerge 2.14.1208 

### ISSUE THREAD

**Issue by XVincentX** [wade/ILMerge.Tools#1]
As the title, your tasks is a bit outdated!

**Comment by wade** [comment]
As stated in the [ReadMe.md file](https://github.com/wade/ILMerge.Tools/blob/master/README.md), the version of this package does not have a hard dependency upon ILMerge and simply calls ILMerge.exe from the command line. You must supply ILMerge.exe and you may use any version that is compatible with the supported command-line arguments, which as of this writing, is ILMerge 2.14.1208 compatible, but also works with many preceding versions and versions that come after so long as no breaking changes have been made to the command-line interface. In fact, that is the entire purpose of this code/package - to loosely couple to ILMerge so that each time a new ILMerge version is released, one does not have to rebind to the assembly to simply integrate with it via MSBuild.

Just to restate more clearly, there is no direct binding or reference to ILMerge from this library nor does it depend upon any specific version of ILMerge nor does it have any direct dependencies upon any specific version of the ILMerge assembly/executable. You must provide your own copy of ILMerge that you obtain from another source (e.g. Microsoft's NuGet package).

Hope this helps,
Wade

**Comment by wade** [comment]
FYI, Mike Barnett created the ILMerge 2.14.1208 package after my request to change the NuGet package to not include ILMerge.exe in the content directory of the package but instead to include it in the tools directory. As far as I know, there is no significant difference between ILMerge 2.14.1203 and ILMerge 2.14.1208.

Wade

**Comment by XVincentX** [comment]
That's the same thing I thought initially, but ILMerge.exe does not recognize.
/allowDuplicateResources, for example!

**Comment by wade** [comment]
I realized you may have been referring to the [ILMerge.Tools](https://www.nuget.org/packages/ILMerge.Tools/) NuGet package, which is a repack of ILMerge. I did just update that package to 2.14.1208. Let me know if that helps.

Wade

**Comment by XVincentX** [comment]
I was referring to [this one](http://www.nuget.org/packages/ILMerge.Tools.MSBuildToolTask/).
For ILMerge I am using the [official one](http://www.nuget.org/packages/ilmerge/)

Am I missing something?

**Comment by wade** [comment]
I see an error in my implementation that I will fix shortly for that command-line switch. It is passing "/allowDuplicateResources" instead of "/allowDup". Sorry for the confusion. I'll let you know once I have fixed it.

Wade

**Comment by XVincentX** [comment]
Exactly! Great. I'll stay online!

**Comment by wade** [comment]
After going back through the code and the ILMerge documentation as well as performing a series of manual tests on the command-line, it appears that the ILMerge Word document does indeed list [/allowDuplicateResources] as an optional switch, the documentation does not elaborate on the switch nor does it list this option in the API reference. For versions 2.14.1203 and 2.14.1208, the documentation is the same and also for both versions, when you execute ilmerge.exe /? for the help, it does NOT display this switch. When this switch is applied to either version, the message, "Ignoring unknown option: 'allowDuplicateResources'," is displayed followed y the help text and the command does not execute.

This appears to be a discrepancy with ILMerge itself. I would contact Mike Barnett directly about it. I will likely remove the option from the MSBuild task since it does not work but instead causes an error.

The 'allowDup' switch is for the 'allow duplicate types' option, not the 'allow duplicate resources' option. Sorry I cannot be of more help on this issue.

Wade

**Comment by wade** [comment]
I have updated the source code and the corresponding [NuGet package](https://www.nuget.org/packages/ILMerge.Tools.MSBuildToolTask/2.14.1208) to version 2.14.1208 in which I have removed support for the "Allow Duplicate Resources" feature because it does not work in ILMerge.exe.

Wade

**Comment by XVincentX** [comment]
Great.
Another point I discovered while using your package.
According to documentation, AllowDuplicateType can be called with null parameter too, which will allow any type to be renamed (see ilmerge.doc).

Actually, your code adds /allowDup options only for specific types. Do you think may you modify this behaviour too?

**Comment by wade** [comment]
Yes, I'll take a look at this later.

**Comment by wade** [comment]
I implemented support for the "/allowDup" switch without any specific type names with the new AllowDuplicateTypeNames which may be set to true to enable the switch. This is supported in the new release of the [ILMerge.Tools.MSBuildToolTask package](https://www.nuget.org/packages/ILMerge.Tools.MSBuildToolTask), version 2.14.1208.49.

Wade

**Comment by XVincentX** [comment]
Definitely amazing! I'm going to try this one right now!
